version: '3'
services:
  app:
    image: random:latest  # Use a prebuilt image instead of building it
    container_name: my-react-app
    ports:
      - "3000:3000"
    # No need for depends_on for the app to wait for nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Assuming custom Nginx config
      - ./build:/usr/share/nginx/html  # Assuming React build files are in the build folder
    # No need for depends_on for nginx to wait for app
